In [26]:
#Q2 Row Echelon Form:

import numpy as np
import sympy as sp

In [73]:

np.random.seed(34)
A=np.random.randint(0,10,(5,5))
A

array([[1, 9, 6, 5, 4],
       [3, 5, 2, 9, 8],
       [6, 5, 6, 4, 5],
       [0, 5, 4, 3, 3],
       [5, 5, 8, 8, 4]])

In [74]:
A[1]=A[1]-3*A[0]
A[2]=A[2]-6*A[0]
A[4]=A[4]-5*A[0]
A

array([[  1,   9,   6,   5,   4],
       [  0, -22, -16,  -6,  -4],
       [  0, -49, -30, -26, -19],
       [  0,   5,   4,   3,   3],
       [  0, -40, -22, -17, -16]])

In [75]:
A[1]=A[1]/-22
A

array([[  1,   9,   6,   5,   4],
       [  0,   1,   0,   0,   0],
       [  0, -49, -30, -26, -19],
       [  0,   5,   4,   3,   3],
       [  0, -40, -22, -17, -16]])

In [76]:
A[2]=A[2]+A[1]*49
A[3]=A[3]-5*A[1]
A[4]=A[4]+40*A[1]
A

array([[  1,   9,   6,   5,   4],
       [  0,   1,   0,   0,   0],
       [  0,   0, -30, -26, -19],
       [  0,   0,   4,   3,   3],
       [  0,   0, -22, -17, -16]])

In [77]:
A[2]=A[2]/-30
A

array([[  1,   9,   6,   5,   4],
       [  0,   1,   0,   0,   0],
       [  0,   0,   1,   0,   0],
       [  0,   0,   4,   3,   3],
       [  0,   0, -22, -17, -16]])

In [78]:
A[3]=A[3]-4*A[2]
A[4]=A[4]+22*A[2]
A

array([[  1,   9,   6,   5,   4],
       [  0,   1,   0,   0,   0],
       [  0,   0,   1,   0,   0],
       [  0,   0,   0,   3,   3],
       [  0,   0,   0, -17, -16]])

In [79]:
A[3]=A[3]/3
A

array([[  1,   9,   6,   5,   4],
       [  0,   1,   0,   0,   0],
       [  0,   0,   1,   0,   0],
       [  0,   0,   0,   1,   1],
       [  0,   0,   0, -17, -16]])

In [80]:
A[4]=A[4]+17*A[3]
A

array([[1, 9, 6, 5, 4],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 1],
       [0, 0, 0, 0, 1]])