In [2]:
#Q3 Singular Value Decomposition 
import numpy as np
import sympy as sp

In [3]:
np.random.seed(34)
A=np.random.randint(0,10,(5,5))
A

array([[1, 9, 6, 5, 4],
       [3, 5, 2, 9, 8],
       [6, 5, 6, 4, 5],
       [0, 5, 4, 3, 3],
       [5, 5, 8, 8, 4]])

In [4]:
U,s,VT= np.linalg.svd(A)
U

array([[-0.4645496 , -0.49259349,  0.51500102, -0.05832695,  0.52241481],
       [-0.48539071,  0.81469407,  0.31304946, -0.04637521,  0.02277732],
       [-0.43694474, -0.10062491, -0.51929534, -0.72562269, -0.05251651],
       [-0.281442  , -0.27613638,  0.34722415,  0.02083738, -0.85061172],
       [-0.52769235, -0.08513849, -0.49652968,  0.68372861,  0.01629961]])

In [5]:
S=np.zeros((A.shape[0], A.shape[1]))
S[:A.shape[1],:A.shape[0]]=np.diag(s)
S

array([[25.58695156,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  6.22838326,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  5.51966431,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  2.88917909,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.83731837]])

In [6]:
VT

array([[-0.28064508, -0.50175166, -0.45832167, -0.5278045 , -0.42526141],
       [ 0.14803952, -0.42858151, -0.5965554 ,  0.47480419,  0.46161112],
       [-0.75081939,  0.51764963, -0.35926239,  0.06969698,  0.18542375],
       [-0.39199566, -0.29838998,  0.26191874,  0.66483889, -0.49667962],
       [ 0.4265352 ,  0.45559351, -0.48620162,  0.22161896, -0.57008359]])

In [7]:
M=U@S@VT
np.round(M)

array([[1., 9., 6., 5., 4.],
       [3., 5., 2., 9., 8.],
       [6., 5., 6., 4., 5.],
       [0., 5., 4., 3., 3.],
       [5., 5., 8., 8., 4.]])

In [8]:
A==np.round(M)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [9]:
# Rank 2 Approximation

A2 = np.dot(U[:, :2], np.dot(np.diag(s[:2]), VT[:2, :]))
np.round(A2)

array([[3., 7., 7., 5., 4.],
       [4., 4., 3., 9., 8.],
       [3., 6., 5., 6., 4.],
       [2., 4., 4., 3., 2.],
       [4., 7., 7., 7., 5.]])

In [10]:
# Rank 3 Approximation
A3 = np.dot(U[:, :3], np.dot(np.diag(s[:3]), VT[:3, :]))
np.round(A3)

array([[1., 9., 6., 5., 4.],
       [3., 5., 2., 9., 8.],
       [5., 4., 7., 5., 4.],
       [0., 5., 4., 3., 3.],
       [6., 6., 7., 7., 5.]])